image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://nickodumo.com
  only:
    - master
  script:
    - npm i -g netlify-cli
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod