// export enum EventType {
//   POINT_OF_SALES_FUNCTION_CLOSE = 'POINT_OF_SALES_FUNCTION_CLOSE',
//   POINT_OF_SALES_FUNCTION_OPEN = 'POINT_OF_SALES_FUNCTION_OPEN',
//   POINT_OF_SALES_TRANSACTION_PAYMENT_ACCEPTED = 'POINT_OF_SALES_TRANSACTION_PAYMENT_ACCEPTED',
//   POINT_OF_SALES_TRANSACTION_PAYMENT_REFUNDED = 'POINT_OF_SALES_TRANSACTION_PAYMENT_REFUNDED',
// }
export const a = 1
